# -*- coding: utf-8 -*-
"""dl_projeto_final.ipynb

Automatically generated by Colaboratory.

Link do projeto no Colab:
    https://colab.research.google.com/drive/1baWw-QPqU0Q1B2Nyn6-ONacHR_GjnVR2
"""
from ultralytics import YOLO
from roboflow import Roboflow

# download do dataset para treino --> roboflow
rf = Roboflow(api_key="KxajJjAGK3Tttlp9z4qc")
project = rf.workspace("ufrn-rr7ed").project("dl_projeto_final")
dataset = project.version(2).download("yolov8")

#os.chdir("/content/drive/MyDrive/Colab Notebooks/treino")
#!pwd

# treinando a rede
#!cat /root/.config/Ultralytics/settings.yaml

#criando folder datasets e movendo dados.
#os.chdir("/content/drive/MyDrive/Colab Notebooks/treino/datasets")
#!pwd
model = YOLO('yolov8n.pt')
results = model.train(data='DL_Projeto_Final-2/data.yaml', epochs=100, imgsz=640)



