# -*- coding: utf-8 -*-
"""dl_projeto_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baWw-QPqU0Q1B2Nyn6-ONacHR_GjnVR2
"""

from google.colab import drive
drive.mount('/content/drive')

# mudando diretorio de trabalho
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks/treino")

#HOME = os.getcwd()
#print(HOME)
!pwd

#install roboflow
!pip install roboflow
from roboflow import Roboflow

# Instalando YOLO
!pip install ultralytics
from ultralytics import YOLO

# download do dataset para treino --> roboflow
os.chdir("/content/drive/MyDrive/Colab Notebooks/treino/datasets")
rf = Roboflow(api_key="KxajJjAGK3Tttlp9z4qc")
project = rf.workspace("ufrn-rr7ed").project("dl_projeto_final")
dataset = project.version(2).download("yolov8")

#os.chdir("/content/drive/MyDrive/Colab Notebooks/treino")
#!pwd

# treinando a rede
!cat /root/.config/Ultralytics/settings.yaml

#criando folder datasets e movendo dados.
os.chdir("/content/drive/MyDrive/Colab Notebooks/treino/datasets")
!pwd
model = YOLO('yolov8x.pt')
results = model.train(data='DL_Projeto_Final-2/data.yaml', epochs=100, imgsz=640)

os.chdir("/content/drive/MyDrive/Colab Notebooks/treino/datasets")

# Predict
!yolo task=detect mode=predict model=runs/detect/train14/weights/best.pt conf=0.25 source=DL_Projeto_Final-2/test/images save=True show_labels=False line_width=2

# imagem de teste
!yolo task=detect mode=predict model=runs/detect/train14/weights/best.pt conf=0.5 source=imagem_teste.jpg save=True show_labels=True line_width=2

# vídeo de teste
!yolo task=detect mode=predict model=runs/detect/train14/weights/best.pt conf=0.6 source=video_teste.mp4 save=True show_labels=True line_width=2

# validando novo modelo
!yolo task=detect mode=val model=runs/detect/train14/weights/best.pt data='DL_Projeto_Final-2/data.yaml'